---

- name: Set Up Hosts
  hosts: all
  become: false
  environment:
    PATH: "/opt/homebrew/bin:/opt/homebrew/sbin:{{ lookup('env', 'PATH') }}"
  vars_files:
    - vars.yaml
  handlers:
    - name: "Restart Dock"
      shell: "killall Dock"
    - name: "Restart Finder"
      shell: "killall Finder"
    - name: "Set Global Python Version To Latest"
      shell: "{{ install_path }}/pyenv global 3"
  tasks:
    - when: ansible_os_family == "Darwin"
      block:
        - name: Install Homebrew Packages
          tags: [ brew, dock, system ]
          ansible.builtin.include_tasks:
            file: macos_tasks/homebrew.yaml
            apply:
              tags: brew
          when: install_homebrew_packages

        - name: Install dockutil.
          tags: [ dock, system ]
          community.general.homebrew:
            name: dockutil
            state: present
          when:
            - homebrew_check.stat.exists or installation_result is succeeded
            - setup_dock

        - name: Register Variables
          tags: always
          block:
          - name: Setting Package Install Path For Non-arm64
            ansible.builtin.set_fact:
              install_path: /usr/local/bin/
            when: ansible_architecture != "arm64"

          - name: Setting Package Install Path For arm64
            ansible.builtin.set_fact:
              install_path: /opt/homebrew/bin
            when: ansible_architecture == "arm64"

        - name: Install Fisher Plugins
          tags: fish
          ansible.builtin.include_tasks:
            file: macos_tasks/fisher.yaml
            apply:
              tags: fish
          when:
            - install_fisher_plugins

        - name: Install System Default Overrides
          tags: [ dock, system ]
          ansible.builtin.include_tasks:
            file: macos_tasks/system.yaml
            apply:
              tags: system
          when: setup_system_defaults

        - name: Install dotfiles
          tags: dotfiles
          ansible.builtin.include_tasks:
            file: macos_tasks/dotfiles.yaml
            apply:
              tags: dotfiles
          when: setup_dotfiles

        - name: Install Nvim Plugins
          tags: nvim
          ansible.builtin.include_tasks:
            file: macos_tasks/nvim.yaml
            apply:
              tags: nvim
          when: install_nvim_plugins

        - name: Installing Latest Python With Pyenv
          tags: python
          ansible.builtin.command:
            cmd: "{{ install_path }}/pyenv install 3"
            creates: ~/.pyenv/shims/python
          notify: Set Global Python Version To Latest
          when: install_python

        - name: Installing Rust
          tags: rust
          shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          args:
            creates: ~/.cargo/bin
          when: install_rust

        - name: Installing Virtualfish
          tags: fish
          ansible.builtin.pip:
            name: virtualfish
          when:
            - fish_is_installed

