---

- name: Set Up Hosts
  hosts: all
  become: false
  environment:
    PATH: "/opt/homebrew/bin:/opt/homebrew/sbin:{{ lookup('env', 'PATH') }}"
  vars_files:
    - vars.yaml
  handlers:
    - name: "Restart Dock"
      shell: "killall Dock"
    - name: "Restart Finder"
      shell: "killall Finder"
  tasks:
    - when: ansible_os_family == "Darwin"
      block:
        - name: Install Homebrew Packages
          tags: [ brew, dock, system ]
          ansible.builtin.include_tasks:
            file: macos_tasks/homebrew.yaml
            apply:
              tags: brew
          when: install_homebrew_packages

        - name: Install dockutil.
          community.general.homebrew:
            name: dockutil
            state: present
          when:
            - homebrew_check.stat.exists or installation_result is succeeded
            - setup_dock
          tags: [ dock, system ]

        - name: Register Variables
          tags: [ fish, nvim ]
          block:
          - name: Setting Package Install Path For Non-arm64
            ansible.builtin.set_fact:
              install_path: /usr/local/bin/
            when: ansible_architecture != "arm64"

          - name: Setting Package Install Path For arm64
            ansible.builtin.set_fact:
              install_path: /opt/homebrew/bin
            when: ansible_architecture == "arm64"

        - name: Install Fisher Plugins
          tags: fish
          ansible.builtin.include_tasks:
            file: macos_tasks/fisher.yaml
            apply:
              tags: fish
          when:
            - install_fisher_plugins

        - name: Install System Default Overrides
          tags: [ dock, system ]
          ansible.builtin.include_tasks:
            file: macos_tasks/system.yaml
            apply:
              tags: system
          when: setup_system_defaults

        - name: Install dotfiles
          tags: dotfiles
          ansible.builtin.include_tasks:
            file: macos_tasks/dotfiles.yaml
            apply:
              tags: dotfiles
          when: setup_dotfiles

        - name: Install Nvim Plugins
          tags: nvim
          ansible.builtin.include_tasks:
            file: macos_tasks/nvim.yaml
            apply:
              tags: nvim
          when: install_nvim_plugins

