---
- name: Ensure Chezmoi Is Installed
  ansible.builtin.stat:
    path: "{{ install_path }}/chezmoi"
  register: chezmoi_is_installed

- name: Setup Dotfiles
  ansible.builtin.command:
    cmd: chezmoi init --apply --verbose {{ dotfiles_repo }}
    creates: ~/.config/chezmoi
  register: chezmoi_result
  when: chezmoi_is_installed

- name: Reporting Chezmoi Result
  tags: [never, debug]
  debug:
    msg: "{{ chezmoi_result.stdout }}"
  when: chezmoi_is_installed
