---

  - name: Ensure Fish Is Installed
    ansible.builtin.stat:
      path: "{{ install_path }}/fish"
    register: fish_is_installed

  - name: Installing Fisherman
    shell: 
      curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | 
        source && fisher install jorgebucaran/fisher
    args:
      executable: "{{ install_path }}/fish"
      creates: ~/.config/fish/fish_plugins
    when: fish_is_installed

  - name: Installing Fisher Plugins
    ansible.builtin.include_tasks: macos_tasks/fish_plugins.yaml
    loop: "{{ fisher_plugins }}"
    when: fish_is_installed

