---

  - name: Ensure Nvim Is Installed
    ansible.builtin.stat:
      path: "{{ install_path }}/nvim"
    register: nvim_is_installed

  - name: Checking If NVim Config Already Exists
    ansible.builtin.stat:
      path: "{{ item }}"
    loop:
      - "~/.config/nvim/init.lua"
      - "~/.config/nvim/init.vim"
    register: nvim_files_exist
    when: nvim_is_installed

  - name: Setting nvim_conf_exists
    ansible.builtin.set_fact:
      nvim_conf_exists: "{{ nvim_files_exist.results | map(attribute='stat.exists') | list is any }}"

  - name: Value Of nvim_conf_exists
    tags: [ never, debug ]
    debug:
      msg: "{{ nvim_conf_exists }}" 

  - name: Installing LazyVim 
    ansible.builtin.git: 
      repo: https://github.com/LazyVim/starter
      dest: ~/.config/nvim
    when:
      - nvim_is_installed
      - not nvim_conf_exists

  - name: Cleaning Up LazyVim Installation 
    file:
      path: ~/.config/nvim/.git
      state: absent
    when:
      - nvim_is_installed
      - not nvim_conf_exists
