---
  - name: Checking If OMF Is Already Installed
    ansible.builtin.stat:
      path: ~/.local/share/omf
    register: omf_check

  - name: Getting OhMyFish Repo
    git:
      repo: 'https://github.com/oh-my-fish/oh-my-fish.git'
      dest: ~/.local/share/temp/oh-my-fish
    when: 
      - not omf_check.stat.exists

  - name: Installing OhMyFish
    shell:
      cmd: "bin/install --offline --noninteractive"
      executable: "{{ install_path }}/fish"
      chdir: ~/.local/share/temp/oh-my-fish
    args:
      creates: ~/.local/share/omf
    when:
      - not omf_check.stat.exists

  - name: Removing OhMyFish Repo
    file:
      path: ~/.local/share/temp/
      state: absent
